DEFAULT_GROUPS:
- BIZ_CLD
- Nx_MGMT
- TEST
- HNAS_FRA
- HNAS_RUS
DEFAULT_OUTPUT_FILE: output.txt
GAD_DEVPFIX: BIZ_CLD
GAD_RES_NAME: UCP_GAD_VSM
LDEVS: 00AA,00AB,00AC
LDEVS_GB: 100,120,120
LDEV_PREFIX:
- BIZ_CLD
- RDM
- GAD_MGMT_Datastore
- SQL
- Nx_MGMT
- TEST
- HNAS_FRA
- HNAS_RUS
POOL_ID:
- '0: Datastore'
- '1: IBM_SVC'
- '2: GENERIC_NL_SAS'
- '10: HNAS'
- '63: UCP Management'
SER_PRI: '443531'
SER_SEC: '414052'
