---
LDEVS: 0000,...
LDEVS_GB: 0,...
POOL_ID:
- '0: Datastore'
- '1: IBM_SVC'
- '2: GENERIC_NL_SAS'
- '10: HNAS'
- '63: UCP Management'
LDEV_PREFIX:
- BIZ_CLD
- RDM
- GAD_MGMT_Datastore
- SQL
- Nx_MGMT
- TEST
- HNAS_FRA
- HNAS_RUS
GAD_DEVPFIX: BIZ_CLD
GAD_RES_NAME: UCP_GAD_VSM
DEFAULT_OUTPUT_FILE: 'output.txt'
DEFAULT_GROUPS:
- BIZ_CLD
- Nx_MGMT
- TEST
- HNAS_FRA
- HNAS_RUS
SER_PRI: '443531'
SER_SEC: '414052'
