DEFAULT_GROUPS: [BIZ_CLD, Nx_MGMT, TEST, HNAS_FRA, HNAS_RUS]
DEFAULT_OUTPUT_FILE: output.txt
GAD_DEVPFIX: BIZ_CLD
GAD_RES_NAME: UCP_GAD_VSM
GB: 1,1,1
LDEVS: 00FF,0100,0101
LDEV_PREFIX: [BIZ_CLD, RDM, GAD_MGMT_Datastore, SQL, Nx_MGMT, TEST, HNAS_FRA, HNAS_RUS]
LDEV_PREFIX_INDEX: 1
POOL_ID: ['0: Datastore', '1: IBM_SVC', '2: GENERIC_NL_SAS', '10: HNAS', '63: UCP
    Management']
REPLICA: ['YES', 'NO']
REPLICA_INDEX: 0
SERIALS: ['443531', '414052']
SERIAL_INDEX: 0
TIER_INDEX: 2
